name: brain-tumor-cnn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pillow
  - tqdm
  - ipywidgets
  - ipykernel
  # CPU-only PyTorch + TorchVision (safe default)
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::cpuonly
  - pip
  - pip:
      # Import name: splitfolders
      - split-folders
      # Import name: torchsummary
      - torchsummary
